### ISSUE TITLE
Make model run on `cuda`

### ISSUE THREAD

**Issue by AdrianM0** [lamalab-org/MoleculeBind#39]
```yaml
name: molbind

channels:
  - conda-forge
  - pytorch
  - pyg
  - nvidia
  - defaults

dependencies:
  - python>=3.9
  - pip
  - faiss-gpu
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu117
    - torch==2.0.0+cu117
    - --editable "."
 ```
